version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: postgres_v2
        PGDATA: /var/lib/postgres/data/postgres_v2 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data_v2
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
