# Generated by Django 2.0.1 on 2018-01-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0008_auto_20180121_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('connection_range', models.CharField(choices=[('Interconnection', 'interconnection'), ('Intraconnection', 'intraconnection')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StoryInEra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyinera',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='confabulation.Story'),
        ),
        migrations.AddField(
            model_name='storyinera',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='confabulation.Era'),
        ),
        migrations.AddField(
            model_name='era',
            name='stories',
            field=models.ManyToManyField(through='confabulation.StoryInEra', to='confabulation.Story'),
        ),
    ]
