# Generated by Django 2.0.1 on 2018-01-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0009_auto_20180121_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='era',
            name='connection_range',
        ),
    ]
