# Generated by Django 2.0.1 on 2018-01-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0011_auto_20180121_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EraPoint',
            new_name='Era',
        ),
        migrations.AddField(
            model_name='story',
            name='era',
            field=models.ManyToManyField(blank=True, null=True, to='confabulation.Era'),
        ),
    ]
